/**
 * Voice-log follow-up clarification logic.
 *
 * Decision lives in pure deterministic code (this file) — `shouldAskFollowUp`.
 * Generation of the natural-language question + chip options is delegated to a
 * cheap LLM call in the worker (see apps/worker/src/processors/stt.processor.ts),
 * driven by the trigger this function returns.
 *
 * Why split it this way:
 *   - Deterministic decision = testable, tunable thresholds, predictable UX.
 *   - LLM decides "what to ask", not "whether to ask".
 *   - One question per voice log (cap), highest-priority trigger wins, on the
 *     item contributing the most calories among triggered items.
 */

export interface VoiceParsedItem {
  name: string;
  quantity: number;
  unit: string;
  grams: number;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  sugar?: number;
  sodium?: number;
  saturatedFat?: number;
  confidence: number;
  /** Fields the model could not extract from the user's speech. */
  missing?: Array<'quantity' | 'unit' | 'preparation' | 'meatType' | 'milkType'>;
  /** Type of ambiguity flagged by the model for this item, if any. */
  ambiguity?: 'meat_type' | 'milk_type' | 'portion' | 'preparation' | null;
}

/** Reason a follow-up was triggered. Each maps to a question style. */
export type FollowUpReason =
  | 'no_items_but_speech'
  | 'missing_quantity'
  | 'meat_type_ambiguous'
  | 'milk_type_ambiguous'
  | 'preparation_ambiguous'
  | 'portion_uncertain'
  | 'low_confidence_high_kcal'
  | 'unrealistic_portion';

export interface FollowUpTrigger {
  reason: FollowUpReason;
  /** Index of the item the question targets, or null if it's about the meal as a whole. */
  itemIndex: number | null;
}

export interface ClarificationOption {
  /** User-facing label (locale-aware, generated by LLM). */
  label: string;
  /**
   * Structured patch to merge into the targeted item when this option is chosen.
   * `null` means "skip" — apply nothing, save with current estimate.
   * Numeric fields override; string fields replace; nullable means clear.
   */
  patch:
    | null
    | (Partial<
        Pick<
          VoiceParsedItem,
          'name' | 'quantity' | 'unit' | 'grams' | 'calories' | 'protein' | 'carbs' | 'fat'
        >
      > & {
        /** Multiplier applied to per-unit kcal/macros if quantity changes (default 1). */
        scaleMacros?: boolean;
      });
}

export interface Clarification {
  question: string;
  options: ClarificationOption[];
  /** Same as the trigger's itemIndex; null = applies to the meal as a whole. */
  itemIndex: number | null;
  reason: FollowUpReason;
}

const HEDGE_REGEX_MN = /(юм\s*уу|жоохон|хэдэн|магадгүй|шиг)/i;
const HEDGE_REGEX_EN = /\b(maybe|some|a bit|kind of|sort of|i think|around|roughly)\b/i;
const GENERIC_FOOD_NAMES = new Set([
  'хоол',
  'мах',
  'шөл',
  'цай',
  'будаа',
  'meat',
  'food',
  'soup',
  'rice',
  'meal',
]);

/**
 * Decide whether the parsed voice log needs a clarifying follow-up question.
 * Returns the highest-priority trigger or null when the data is good enough
 * to save as-is.
 *
 * Priority (highest first):
 *   1. transcription has speech but no items → ask what they ate
 *   2. high-kcal item with quantity missing → ask portion
 *   3. high-kcal item with explicit ambiguity flag (meat_type / milk_type / preparation / portion)
 *   4. high-kcal item with confidence < 0.65
 *   5. unrealistic portion (kcal/g out of [0.3, 9])
 *
 * "High-kcal" = item contributes ≥20% of total kcal, OR is the only item.
 */
export function shouldAskFollowUp(
  items: VoiceParsedItem[],
  transcription: string,
): FollowUpTrigger | null {
  const cleaned = (transcription ?? '').trim();
  if (cleaned.length === 0) return null;

  if (items.length === 0) {
    return { reason: 'no_items_but_speech', itemIndex: null };
  }

  const totalKcal = items.reduce((s, i) => s + Math.max(0, i.calories), 0);
  const isHighKcal = (idx: number) => {
    if (items.length === 1) return true;
    if (totalKcal <= 0) return false;
    return items[idx].calories / totalKcal >= 0.2;
  };

  const hedged = HEDGE_REGEX_MN.test(cleaned) || HEDGE_REGEX_EN.test(cleaned);

  // 2. Missing quantity on a high-kcal item.
  for (let i = 0; i < items.length; i++) {
    const it = items[i];
    if (!isHighKcal(i)) continue;
    const missingQuantity =
      it.missing?.includes('quantity') || it.quantity == null || it.quantity <= 0;
    if (missingQuantity) {
      return { reason: 'missing_quantity', itemIndex: i };
    }
  }

  // 3. Ambiguity flag on a high-kcal item — pick highest-kcal first.
  const ambiguousIdx = items
    .map((it, i) => ({ it, i }))
    .filter(({ it, i }) => isHighKcal(i) && it.ambiguity != null)
    .sort((a, b) => b.it.calories - a.it.calories)[0];
  if (ambiguousIdx) {
    const ambiguity = ambiguousIdx.it.ambiguity;
    let reason: FollowUpReason = 'preparation_ambiguous';
    if (ambiguity === 'meat_type') reason = 'meat_type_ambiguous';
    else if (ambiguity === 'milk_type') reason = 'milk_type_ambiguous';
    else if (ambiguity === 'preparation') reason = 'preparation_ambiguous';
    else if (ambiguity === 'portion') reason = 'portion_uncertain';
    return { reason, itemIndex: ambiguousIdx.i };
  }

  // 4. Low confidence on a high-kcal item — pick lowest confidence first.
  const lowConfIdx = items
    .map((it, i) => ({ it, i }))
    .filter(({ it, i }) => isHighKcal(i) && it.confidence < 0.65)
    .sort((a, b) => a.it.confidence - b.it.confidence)[0];
  if (lowConfIdx) {
    return { reason: 'low_confidence_high_kcal', itemIndex: lowConfIdx.i };
  }

  // 5. Unrealistic portion: kcal/gram outside reasonable bounds.
  // Only on dominant items — a tiny side-item with weird density isn't worth
  // interrupting the user for.
  for (let i = 0; i < items.length; i++) {
    if (!isHighKcal(i)) continue;
    const it = items[i];
    if (it.grams <= 0 || it.calories <= 0) continue;
    const density = it.calories / it.grams;
    if (density < 0.3 || density > 9) {
      return { reason: 'unrealistic_portion', itemIndex: i };
    }
  }

  // Hedge words alone don't trigger if the model otherwise reported high
  // confidence — the user just speaks tentatively. But if confidence is
  // already borderline (0.65–0.75) AND hedge words present, treat as low-conf.
  if (hedged) {
    const borderlineIdx = items
      .map((it, i) => ({ it, i }))
      .filter(({ it, i }) => isHighKcal(i) && it.confidence < 0.75)
      .sort((a, b) => a.it.confidence - b.it.confidence)[0];
    if (borderlineIdx) {
      return { reason: 'low_confidence_high_kcal', itemIndex: borderlineIdx.i };
    }
  }

  // Generic food names like "мах" / "soup" alone — flag as ambiguous if not
  // already qualified.
  for (let i = 0; i < items.length; i++) {
    const it = items[i];
    if (!isHighKcal(i)) continue;
    const lower = it.name.trim().toLowerCase();
    if (GENERIC_FOOD_NAMES.has(lower)) {
      return { reason: 'preparation_ambiguous', itemIndex: i };
    }
  }

  return null;
}
